#!/bin/bash

echo "==delete bucket=="

# Check for an argument to the script
if [ $# -eq 0 ]; then
    echo "No bucket name provided"
    exit 1
fi

BUCKET_NAME=$1

# https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/create-bucket.html 
aws s3api delete-bucket \
--bucket $BUCKET_NAME 
