#!/bin/bash

echo "== deploy S3 bucket via CF =="

STACK_NAME="cfn-s3-simple"
aws cloudformation deploy \
--template-file template.yaml \
--region us-west-1 \
--stack-name $STACK_NAME \
--no-execute-changeset